management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always

ticket:
  calculator: defaultTicketCalculator
  pricing:
    adult: 25.0
    senior-discount: 0.3
    teen: 12.0
    children: 5.0
    children-discount-threshold: 3
    children-discount: 0.25